### ISSUE TITLE
place todo list (infinite canvas version)

### ISSUE THREAD

**Issue by sheminusminus** [laarc/laarc#5]
- [ ] touch events

- [ ] stationary color palette

- [ ] draw what's out of view when it comes into view

- [ ] pan on drag instead of pressing 'd'

- [ ] click to color
